name = "ana-mission-control"
pages_build_output_dir = "."
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "mission-control-db"
database_id = "0ad5c5b6-001b-40bf-81bb-64a954fbb86e"
